server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gmall_study?useUnicode=true&amp&characterEncoding=UTF-8&amp&serverTimezone=GMT%2B8
    username: root
    password: admin



mybatis:
  #实体类所在包名
  type-aliases-package: com.atguigu.gmall.user.bean
  #通用mapper配置
  mapper:
    #公用接口类路径
    mappers: com.atguigu.gmall.user.baseDao.IBaseDao
    identity: MYSQL

